### PR TITLE
proxy compatibility

### PR DESCRIPTION
**Pull request by DPS0340**
i edit the code a little.
would you pull it? :D

### CODE REVIEW

**Comment by palewire** [comment]
I'm okay with this idea, but I think I'd prefer to add as little code as possible. I have an alternative idea I'm going to try real quick.

**Comment by palewire** [comment]
I just shipped a new version to PyPI that supports proxies. It's not as integrated as your work, but I think will accomplish the same task. I added a "proxies" kwarg to the capture function that will pass along a dictionary to the proxies kwarg on requests. Let me know if this will work for you.

**Comment by DPS0340** [comment]
i'll check it. thanks for the help.

**Comment by DPS0340** [comment]
tested it. your code shows me a better way!

**Pull request closed without merging**
